#:schema https://yazi-rs.github.io/schemas/yazi.json

[tasks]
image_alloc = 0
image_bound = [0, 0]
suppress_preload = true

[mgr]
sort_by = "natural"
show_hidden = true
show_symlink = false
linemode = "mtime"

[preview]
wrap = "yes"
image_filter = "lanczos3"
image_delay = 0

# i am use an gui editor, so i don't need to block the terminal when opening a file
# [[opener.edit]]
# run = "%EDITOR% %s"
# desc = "$EDITOR (block)"
# block = true
# for = "windows"

[[opener.edit]]
run = "%EDITOR% %s"
desc = "$EDITOR (orphan)"
orphan = true
for = "windows"

[[opener.open]]
run = 'start "" %s1'
desc = "Open"
for = "windows"
orphan = true

[[opener.open]]
run = 'sudo start "" %s1'
desc = "Open with sudo"
for = "windows"
orphan = true

[[opener.open]]
run = '"C:\Program Files\Sandboxie-Plus\Start.exe" /box:__ask__ %s1'
desc = "Open With Sandboxie"
for = "windows"

[[opener.copyimage]]
# if file name contains space, it will be treated as multiple arguments
run = '{nu} --commands "clip copy-image %s"'
desc = "Copy Image to Clipboard"
for = "windows"

[[opener.get-dll]]
run = '{nu} --commands "(get-dll %s1);pause"'
desc = "Get DLL Path"
for = "windows"
block = true

[[opener.extract]]
run = "Bandizip bx -target:auto - %s"
desc = "Extract with Bandizip cli"
for = "windows"

[[opener.extract]]
run = "Bandizip %s"
desc = "Extract with Bandizip"
for = "windows"

[[opener.extract]]
run = "ya pub augmented-extract --list %s"
desc = "Extract here(augmented)"

[[opener.nodejs]]
run = 'start {nu} --commands "node %s;pause"'
desc = "Run with Node.js"
orphan = true

[[opener.python]]
run = 'start {nu} --commands "uv run %s;pause"'
desc = "Run with Python"
orphan = true

[[opener.bat]]
run = 'start cmd /c "%s"'
desc = "Run with cmd"
for = "windows"
orphan = true

[[opener.lazydocker]]
run = "lazydocker -f %s"
desc = "Open with LazyDocker"
block = true

[[opener.cargo-install]]
run = "cargo install --path %d"
desc = "Install Cargo Package"

[[opener.justfile]]
run = "just --justfile %s --choose --chooser \"fzf --multi --preview 'just --unstable --color always --justfile \"%s\" --show {}'\""
desc = "Run Justfile"
block = true

[[opener.add-to-path]]
desc = "Add to PATH"
run = '''
pwsh -Command "[Environment]::SetEnvironmentVariable('PATH', [Environment]::GetEnvironmentVariable('PATH', 'User') + ';%s', 'User')"
'''
for = "windows"

[[opener.hash-check]]
desc = "Check Hash"
run = '{nu} --commands "ezcheck check --check-file %s;pause"'
block = true

[[opener.bulk-rename]]
run = "code-insiders --wait %s"
block = true

[[opener.bulk-create]]
run = "code-insiders --wait %s"
block = true

[[open.rules]]
url = "bulk-rename.txt"
use = "bulk-rename"

[[open.rules]]
url = "bulk-create.txt"
use = "bulk-create"

[[open.rules]]
mime = "trash/**"
use = ["open", "edit", "trash"]

[[open.rules]]
url = "**/sha256sum.txt"
use = [
  "hash-check",
  "edit",
  "reveal",
]

[[open.rules]]
url = "**/*.bat"
use = [
  "bat",
  "edit",
  "reveal",
]

[[open.rules]]
url = "**/docker-compose.yaml"
use = [
  "lazydocker",
  "edit",
  "reveal",
]

[[open.rules]]
url = "**/Cargo.toml"
use = [
  "cargo-install",
  "edit",
  "reveal",
]

[[open.rules]]
url = "**/{justfile,.justfile,*.just}"
use = [
  "justfile",
  "edit",
  "reveal",
]

[[open.rules]]
url = "*.exe"
use = [
  "open",
  "get-dll",
  "reveal",
]

[[open.rules]]
mime = "image/gif"
use = [
  "play",
  "reveal",
]

# image
[[open.rules]]
mime = "image/*"
use = [
  "open",
  "copyimage",
  "reveal",
]

# media
[[open.rules]]
mime = "{audio,video}/*"
use = [
  "play",
  "reveal",
]

# jar file is actually a zip archive, but it's more user-friendly to open it with java
[[open.rules]]
mime = "application/java-archive"
use = [
  "open",
  "extract",
  "reveal",
]

[[open.rules]]
mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}"
use = [
  "extract",
  "reveal",
]

[[open.rules]]
# data
mime = "*/{json,ndjson,yaml}"
use = [
  "edit",
  "reveal",
]

[[open.rules]]
# code
mime = "*/javascript"
use = [
  "nodejs",
  "edit",
  "reveal",
]

[[open.rules]]
mime = "text/python"
use = [
  "python",
  "edit",
  "reveal",
]

[[open.rules]]
mime = "inode/empty"
use = [
  "edit",
  "reveal",
]

[[open.rules]]
mime = "vfs/{absent,stale}"
use = "download"

[[open.rules]]
url = "*"
use = [
  "open",
  "edit",
  "reveal",
]

[[open.rules]]
mime = "folder/*"
use = [
  "edit",
  "add-to-path",
  "reveal",
]

# fetchers
# </ https://github.com/yazi-rs/plugins/tree/main/mime-ext.yazi
[[plugin.prepend_fetchers]]
url = "local://*"
run = "mime-ext.local"
prio = "high"
group = "mime"

[[plugin.prepend_fetchers]]
url = "remote://*"
run = "mime-ext.remote"
prio = "high"
group = "mime"
# https://github.com/yazi-rs/plugins/tree/main/mime-ext.yazi />

# </ https://github.com/yazi-rs/plugins/tree/main/git.yazi
[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"
# https://github.com/yazi-rs/plugins/tree/main/git.yazi />

# previewers
# </ https://github.com/AminurAlam/yazi-plugins/tree/main/preview-git.yazi
[[plugin.prepend_previewers]]
url = "**/.git/"
run = "preview-git"
# https://github.com/AminurAlam/yazi-plugins/tree/main/preview-git.yazi />

# </ https://github.com/boydaihungst/mediainfo.yazi
[[plugin.prepend_previewers]]
mime = "{audio,video,image}/*"
run = "mediainfo"

[[plugin.prepend_previewers]]
mime = "application/{subrip,postscript,illustrator,dvb.ait,vnd.adobe.illustrator,eps}"
run = "mediainfo"
# https://github.com/boydaihungst/mediainfo.yazi />

# </ user
[[plugin.prepend_previewers]]
url = "*.bat"
run = "code"

[[plugin.prepend_previewers]]
mime = "application/{xml,sql}"
run = "code"

[[plugin.prepend_previewers]]
mime = "{text/x-nushell,application/x-nuon}"
run = "piper -- def main [path: path] {open --raw $path | nu-highlight}"

[[plugin.prepend_previewers]]
mime = "application/java-archive"
run = "archive"

# user />

# preloaders
# </ https://github.com/boydaihungst/mediainfo.yazi
[[plugin.prepend_preloaders]]
mime = "{audio,video,image}/*"
run = "mediainfo"

[[plugin.prepend_preloaders]]
mime = "application/{subrip,postscript,illustrator,dvb.ait,vnd.adobe.illustrator,eps}"
run = "mediainfo"
# https://github.com/boydaihungst/mediainfo.yazi />

# spotters
# </ https://github.com/AminurAlam/yazi-plugins/tree/main/spot.yazi
# [[plugin.prepend_spotters]]
# mime = "audio/*"
# run = "spot-audio"

# [[plugin.prepend_spotters]]
# mime = "image/*"
# run = "spot-image"

# [[plugin.prepend_spotters]]
# mime = "video/*"
# run = "spot-video"

# [[plugin.prepend_spotters]]
# mime = "folder/*"
# run = "spot"

# [[plugin.prepend_spotters]]
# url = "*"
# run = "spot"
# https://github.com/AminurAlam/yazi-plugins/tree/main/spot.yazi />
