#:schema https://starship.rs/config-schema.json

format = "$all"
right_format = "${env_var.yazi_level}$shlvl$cmd_duration$battery"

add_newline = false

[profiles]
transient_prompt = "$time$directory[\\$](#727272) "
transient_prompt_right = ""

[battery]
disabled = false

[[battery.display]]
threshold = 50

[shlvl]
disabled = false

[git_metrics]
disabled = false

[directory]
truncation_length = 5
truncation_symbol = ".../"
read_only = " 󰌾"

[env_var.yazi_level]
description = "Indicate the shell was launched by `yazi`"
variable = "YAZI_LEVEL"
symbol = " "
format = "[$symbol]($style)"
style = "yellow bold"

[status]
disabled = false

[direnv]
disabled = false
detect_files = [".envrc", ".env"]
